config/routes.rb
Rails.application.routes.draw do
  mount ClipUploader.upload_endpoint(:cache) => "/clips/upload"
  mount Shrine.presign_endpoint(:cache) => "/clips/presign"

  # root to: 'static#welcome', constraints:
  #   lambda { |request| request.env['warden'].user == nil }

  # root to: 'accounts#usage', constraints:
  #   lambda { |request| request.env['warden'].user.viewer? }

  # root to: 'accounts#dashboard', constraints:
  #   lambda { |request| request.env['warden'].user.uploader? }

  root to: 'videos#index'

  devise_for :users, controllers: { sessions: 'users/sessions',
                                  registrations: "users/registrations",
                                  omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  resources :charges

  resources :videos do
    member do
      patch 'remove'
      patch 'restore'
    end
  end

  resources :plays
  resources :embeds

  resources :blogs, constraints: { subdomain: 'blog' }

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'

  patch 'accounts', to: 'accounts#update'
  get 'accounts/edit', to: 'accounts#edit'
  get 'accounts/show' , to: 'accounts#show'
  get 'dashboard', to: 'accounts#dashboard'
  get 'usage', to: 'accounts#usage'
  get 'library', to: 'users#library'
  get 'account', to: 'accounts#show'
  get 'search', to: 'videos#search'
  get 'landing', to: 'embeds#landing'
  get 'video_test/:id', to: 'video_test#show'
  get 'buy_message', to: 'embeds#buy_message'
  get 'thank_you', to: 'embeds#thank_you'
  get 'stats', to: 'static#stats'


  get 'sessions/impersonate', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :users
    resources :videos do
      member do
        patch 'toggle_approval'
        patch 'toggle_featured'
        patch 'toggle_suspended'
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
  end

  devise_scope :user do
      namespace :users do
        get 'sessions/present', to: "sessions#present"
      end
  end
end

app/models/user.rb
class User < ApplicationRecord

  after_create :create_account

  #other modules: :lockable, :timeoutable
  has_many :videos, dependent: :destroy
  has_one :account, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  devise :omniauthable, :omniauth_providers => [:facebook] #todo: remove?

  def create_account
    account = Account.new(user_id: id, image: Rails.configuration.default_profile_image)
    if account.save
      print "Account created!!"
    else
      print account.errors.full_messages
    end
  end

  def uploader?
    videos.any?
  end

  def viewer?
    !uploader?
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.full_name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.all
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      puts @user.errors.full_messages
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   if current_user.uploader?
  #     new_video_path
  #   else
  #     super
  #   end
  # end

  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   if current_user.uploader?
  #     new_video_path
  #   else
  #     super
  #   end
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create

    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def present
    if user_signed_in?
      render json: { "logged_in" => "true" }
    else
      render json: { "logged_in" => "false"}
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:library]
  def library
    @videos = current_user.videos.unremoved
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/library.html.erb
<% provide(:title, "Library") %>
<div class="row">
  <div class="col">
    <% if @videos %>
      <table class="table library-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Duration</th>
            <th>Views</th>
            <th>Date Added</th>
          </tr>
        </thead>
        <tbody>
          <% @videos.order(created_at: :desc).each do |video| %>
            <tr onclick="window.location = '<%= edit_video_path(video) %>' ">
              <td><%= video.title %></td>
              <td><%= youtube_time(video.duration) %></td>
              <td><%= video.minutes %></td>
              <td><%= video.created_at.to_formatted_s(:db) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>

    <br><p>You don't have any uploaded videos yet. <%= link_to "Upload videos", new_video_path %></p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.full_name) %>
<br>
<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="profile-card">
      <div class="profile-pic">
        <%= cl_image_tag @user.account.image, client_hints: true, transformation: [ 
                          { gravity: "auto", width: "150", height: "150", radius: "max", crop: "fill" }] %>
      </div>
      <div class="loader"></div>
      <div>
        <h4><%= @user.full_name %></h4>
      </div>
      <div class="stats">
        <span><%= @user.videos.count %> Videos</span> | 
        <span><%= @user.account.balance %> Minutes</span>
      </div>
    </div>
  </div>
  <div class="col-md-4 text-right">
    <% if @user == current_user %>
      <%= form_with scope: :account, url: "/accounts", method: :patch do |form| %>
        <label class="btn-link text-center">Change profile photo
         <%= cl_image_upload_tag(:image_id, aria_hidden: true, id: "file-upload-br") %>
        </label>
        <br>
          <%= form.submit "Update", class: "btn btn-primary profile-save" %>
      <% end %>
    <% end %>
  </div>
</div>


<hr>
<div class="row">
  <% @user.videos.each do |video| %>
    <div class="col-md-4">
      <div class="br-card">
        <%= link_to video_path(video), class: "br-card-link" do %>
          <%= cl_image_tag(video.image, :client_hints=>true, :transformation=>[
          {:aspect_ratio=>"16:9", :gravity=>"auto", :crop=>"fill"},
          {:width=>"auto", :quality=>"auto", :fetch_format=>:auto, :crop=>"scale"}
          ]) %>
        <% end %>
        <div class="br-card-body">
          <div class="mb-2">
            <%= link_to video_path(video), class: "br-card-link br-card-title" do %>
              <%= video.title %>
              <!-- make div clickable -->
              <span></span>
            <% end %>
          </div>
          <div>
            <%= link_to video.user.full_name, user_path(video.user), class: "br-card-link fuck text-secondary user-link" %>
          </div>
          <div>
            <%= link_to "#{video.minutes} Views", video_path(video), class: "br-card-link text-secondary" %> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<script>
  $(function() {
    if($.fn.cloudinary_fileupload !== undefined) {

      $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload({
      });

      $('.cloudinary-fileupload').bind('fileuploadadd', function(e, data) { 
        $(".loader").show();
      });

      $('.cloudinary-fileupload').bind('fileuploadprogress', function(e, data) { 
        console.log(data);
      });

      $('.cloudinary-fileupload').bind('cloudinarydone', function(e, data) {  
        var id = data.result.public_id;
        var format = data.result.format;
        var version = data.result.version;
        var url = "https://res.cloudinary.com/eli/image/upload/w_150,h_150,c_fill,g_auto,r_max/v" + version + "/" + id + "." + format;
        $(".profile-pic img").attr("src", url);
        $(".loader").hide();
        $(".profile-save").show();
        console.log(id, format, version, url);
      });
    }
  });
</script>