config/routes.rb
Rails.application.routes.draw do
  mount ClipUploader.upload_endpoint(:cache) => "/clips/upload"
  mount Shrine.presign_endpoint(:cache) => "/clips/presign"

  # root to: 'static#welcome', constraints:
  #   lambda { |request| request.env['warden'].user == nil }

  # root to: 'accounts#usage', constraints:
  #   lambda { |request| request.env['warden'].user.viewer? }

  # root to: 'accounts#dashboard', constraints:
  #   lambda { |request| request.env['warden'].user.uploader? }

  root to: 'videos#index'

  devise_for :users, controllers: { sessions: 'users/sessions',
                                  registrations: "users/registrations",
                                  omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users
  resources :charges

  resources :videos do
    member do
      patch 'remove'
      patch 'restore'
    end
  end

  resources :plays
  resources :embeds

  resources :blogs, constraints: { subdomain: 'blog' }

  get 'about', to: 'static#about'
  get 'contact', to: 'static#contact'
  get 'privacy', to: 'static#privacy'
  get 'terms', to: 'static#terms'

  patch 'accounts', to: 'accounts#update'
  get 'accounts/edit', to: 'accounts#edit'
  get 'accounts/show' , to: 'accounts#show'
  get 'dashboard', to: 'accounts#dashboard'
  get 'usage', to: 'accounts#usage'
  get 'library', to: 'users#library'
  get 'account', to: 'accounts#show'
  get 'search', to: 'videos#search'
  get 'landing', to: 'embeds#landing'
  get 'video_test/:id', to: 'video_test#show'
  get 'buy_message', to: 'embeds#buy_message'
  get 'thank_you', to: 'embeds#thank_you'
  get 'stats', to: 'static#stats'


  get 'sessions/impersonate', to: 'sessions#impersonate'


  namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    resources :users
    resources :videos do
      member do
        patch 'toggle_approval'
        patch 'toggle_featured'
        patch 'toggle_suspended'
      end
    end
    get 'sessions/:id', to: 'sessions#impersonate', as: "impersonate"
  end

  devise_scope :user do
      namespace :users do
        get 'sessions/present', to: "sessions#present"
      end
  end
end

app/controllers/embeds_controller.rb
class EmbedsController < ApplicationController
  def show
    @video = Video.find(params[:id])

    if @video.removed || @video.suspended
      render 'unavailable'
    end

    if user_signed_in?
      if current_account.balance < @video.duration
        redirect_to buy_message_path
        session[:video_id] = @video.id
        session[:ref] = 'embed'
      end
    else
      redirect_to landing_path(video_id: @video.id)
    end
  end

  def landing
    @video = Video.find(params[:video_id])
  end

  def buy_message
    @video = Video.find(session[:video_id])
    unless current_account.balance < @video.duration
      redirect_to embed_path(@video.id)
    end
  end

  def thank_you
  end

end

app/helpers/embeds_helper.rb
module EmbedsHelper
end

app/views/embeds/buy_message.html.erb
<div class="text-white embedded-signup bg-dark">

  <p class="text-center">Not enough minutes to view this video. Buy more for &cent;1/min.</p>
  <div class="embedded-links">
    <%= link_to "Buy minutes", new_charge_path, 
                class: "btn btn-primary", target: "blank", video_id: @video.id %>
                
  </div>
  <div class="video-background">

  </div>
</div>


<script>
  document.querySelector("body").setAttribute("id", "embed-body");
  var videoBackground = document.querySelector(".video-background");
  videoBackground.style.background = "url(<%= @video.image_url %>)";
</script>

app/views/embeds/landing.html.erb
<div class="text-white embedded-signup bg-dark">
  <div class="signup-form">  
    <h4 class="text-center">Premium Video</h4>
    <p class="text-center">Sign up with Browzable and get free minutes to view this video</p>
    <div class="embedded-links">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary", target: "blank", ref: @video.id %>
       <span class="mr-4 ml-4">Or</span>
       <%= link_to "Log in", new_user_session_path, class: "btn btn-primary", target: "blank" %>
     </div>
  </div>
  <div class="video-background">

  </div>
</div>


<script>
  document.querySelector("body").setAttribute("id", "embed-body");
  var videoBackground = document.querySelector(".video-background");
  videoBackground.style.background = "url(<%= @video.image_url %>)";
</script>

app/views/embeds/show.html.erb
<%= render 'shared/player' %>

  

app/views/embeds/thank_you.html.erb
<%= render 'layouts/nav' %>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>Thank you!</h4>
      <p>Refresh the page you came from and you will now be able to watch your video. You can view your new minutes balance at the top left of this page, and in your video player as well.</p>
    </div>
  </div>
</div>

app/views/embeds/unavailable.html.erb
Video unavailable.